// Filesystem layout shared by the UI isolate (which connects to the daemon's
// control socket) and the foreground-service isolate (which spawns the daemon).
// Both must agree on every path, so it all lives here as pure functions of the
// native paths.

import 'dart:io';

import 'native_bridge.dart';

class FilestrLayout {
  final NativePaths paths;
  FilestrLayout(this.paths);

  String get runDir => '${paths.filesDir}/run';
  String get socketPath => '$runDir/filestrd.sock';
  String get configPath => '${paths.filesDir}/config.toml';
  String get shareDir => '${paths.filesDir}/share';
  String get downloadsDir => '${paths.filesDir}/downloads';
  String get logPath => '${paths.filesDir}/filestrd.log';
  String get daemonBinary => paths.daemonBinary;

  /// Loopback HTTP gateway port (for a Grayjay plugin etc. on this device).
  static const int httpPort = 11780;

  /// Pin every XDG root inside the app sandbox so the daemon never writes
  /// outside it.
  Map<String, String> env() => {
        'HOME': paths.filesDir,
        'XDG_RUNTIME_DIR': runDir,
        'XDG_CONFIG_HOME': '${paths.filesDir}/config',
        'XDG_DATA_HOME': '${paths.filesDir}/data',
        'XDG_STATE_HOME': '${paths.filesDir}/state',
        'XDG_CACHE_HOME': paths.cacheDir,
        'RUST_LOG': 'info',
      };

  /// Write the daemon config (chat off — the bundled binary has no chat at
  /// all) and ensure the directories it needs exist.
  Future<void> writeConfig() async {
    await Directory(runDir).create(recursive: true);
    await Directory(shareDir).create(recursive: true);
    await Directory(downloadsDir).create(recursive: true);
    final config = '''
# Generated by filestr_app. Do not edit while the app is running.
data_dir = "${paths.filesDir}/data"
relay = "default"

[chat]
enabled = false

[http]
listen = "127.0.0.1:$httpPort"

[[share]]
name = "shared"
path = "$shareDir"
''';
    await File(configPath).writeAsString(config);
  }
}
