[package]
name = "filestr-chat"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.102"
data-encoding = "2.11.0"
libfilestr = { path = "../libfilestr" }
mdk-core = "0.8.0"
mdk-memory-storage = "0.8.0"
nostr = { version = "0.44.3", features = ["nip44"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["rt", "sync", "io-util", "macros", "time"] }
tracing = "0.1.44"
